# Pocket Money Tracker
A lightweight, professional desktop application built with Python to help you manage your daily finances. This tool provides a clean interface to track your income and expenses in real-time without the need for complex spreadsheets.

## Features
* Live Balance Dashboard: A high-visibility header that updates instantly as you add or spend money.
* Transaction Logging: Record expenses with categories and descriptions to see exactly where your money goes.
* Persistent Storage: Automatically saves your data to a data.json file. Your balance stays saved even after you close the app.
* Visual History Table: A scrollable table that displays your transaction history including Date, Category, and Amount.
* Input Validation: Built-in error handling to prevent invalid data entries, such as entering text into a numerical field.

## Technical Stack
* Language: Python 3.12+
* GUI Framework: Tkinter (Standard Python Library)
* Data Format: JSON (JavaScript Object Notation) for local storage.

## Installation and Execution
1. Install Python: Ensure you have Python 3.12 or higher installed on your machine.
2. Clone or Download: Place the project files in a dedicated folder.
3. Run the Application: Open your terminal or command prompt in the project directory and execute:
   python main.py

## Project Structure
* main.py: The core application file containing the GUI logic and calculation engine.
* data.json: This file is automatically generated and stores your current balance and full expense history.
* README.md: The documentation file you are currently reading.

## System Logic
1. Initialization: On startup, the application attempts to load data from data.json. If the file is missing, it initializes a new data structure with a zero balance.
2. Income Processing: When an amount is entered and the "Add" button is clicked, the application updates the memory state and immediately synchronizes with the JSON file.
3. Expense Processing: The system captures the amount, category, and description. It performs a balance check to ensure sufficient funds exist before deducting the amount and logging the entry.
4. Data Persistence: Every successful transaction invokes a saving routine to ensure data integrity even in the event of an unexpected shutdown.
5. UI Synchronization: The interface is programmed to refresh all labels and table views immediately following any data modification.

## Future Enhancements
* Implementation of expense filtering by date ranges.
* Visual data representation using charts and graphs.
* Functionality to edit or delete existing transaction entries.

This project was developed with a focus on clean code architecture and practical financial management.
